lib/alloy_ci/web/router.ex
defmodule AlloyCi.Web.Router do
  use AlloyCi.Web, :router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  # This plug will look for a Guardian token in the session in the default location
  # Then it will attempt to load the resource found in the JWT.
  # If it doesn't find a JWT in the default location it doesn't do anything
  pipeline :browser_auth do
    plug(AlloyCi.Guardian.Pipeline)
  end

  # This pipeline is created for use within the admin namespace.
  # It looks for a valid token in the session - but in the 'admin' location of guardian
  # This keeps the session credentials separate for the main site, and the admin site
  # It's very possible that a user is logged into the main site but not the admin
  # or it could be that you're logged into both.
  # This does not conflict with the browser_auth pipeline.
  # If it doesn't find a JWT in the location it doesn't do anything
  pipeline :admin_browser_auth do
    plug(AlloyCi.Guardian.AdminPipeline)
  end

  # We need this pipeline to load the token when we're impersonating.
  # We don't want to load the resource though, just verify the token
  pipeline :impersonation_browser_auth do
    plug(Guardian.Plug.VerifySession, key: :admin)
  end

  pipeline :api do
    plug(:accepts, ["json", "text"])
  end

  pipeline :github do
    plug(AlloyCi.Plugs.GithubHeader)
  end

  # This pipeline if intended for API requests and looks for the JWT in the "Authentication" header
  # In this case, it should be prefixed with "Bearer" so that it's looking for
  # Authentication: Bearer <jwt>
  pipeline :api_auth do
    plug(Guardian.Plug.VerifyHeader, realm: "Bearer")
    plug(Guardian.Plug.LoadResource)
  end

  scope "/", AlloyCi.Web do
    # We pipe this through the browser_auth to fetch logged in people
    # We pipe this through the impersonation_browser_auth to know if we're impersonating
    # We don't just pipe it through admin_browser_auth because that also loads the resource
    pipe_through([:browser, :browser_auth, :impersonation_browser_auth])
    get("/", PublicController, :index)
    get("/register", PublicController, :register, as: :register)

    delete("/logout", AuthController, :logout)

    resources("/notifications", NotificationController, only: [:index, :delete, :update])
    post("/notifications/acknowledge_all", NotificationController, :acknowledge_all)
    post("/notifications/delete_all", NotificationController, :delete_all)

    resources("/profile", ProfileController, only: [:index, :update, :delete])
    delete("/profile/:auth_id/delete", ProfileController, :delete, as: :auth_delete)

    resources "/projects", ProjectController do
      resources("/pipelines", PipelineController, only: [:create, :delete, :show])

      resources("/builds", BuildController, only: [:show, :create, :update]) do
        get("/artifact", BuildController, :artifact, as: :artifact)
        post("/artifact/keep", BuildController, :keep_artifact, as: :keep_artifact)
      end

      resources("/badge/:ref", BadgeController, only: [:index])
    end

    resources("/runners", RunnerController, only: [:show, :delete, :update])

    resources("/tokens", TokenController, only: [:delete])
  end

  # This scope is the main authentication area for Ueberauth
  scope "/auth", AlloyCi.Web do
    # Use the default browser stack
    pipe_through([:browser, :browser_auth])

    get("/:provider", AuthController, :login)
    get("/:provider/callback", AuthController, :callback)
    post("/:provider/callback", AuthController, :callback)
  end

  # This scope is intended for admin users.
  # Normal users can only go to the login page
  scope "/admin", AlloyCi.Web.Admin, as: :admin do
    # Use the default browser stack
    pipe_through([:browser])

    get("/login", SessionController, :new, as: :login)
    get("/login/:provider", SessionController, :new)
    post("/auth/:provider/callback", SessionController, :callback)
  end

  scope "/admin", AlloyCi.Web.Admin, as: :admin do
    pipe_through([:browser, :admin_browser_auth])

    get("/logout", SessionController, :logout)
    delete("/logout", SessionController, :logout, as: :logout)
    post("/impersonate/:user_id", SessionController, :impersonate, as: :impersonation)
    delete("/impersonate", SessionController, :stop_impersonating)

    resources("/users", UserController, only: [:index, :show, :delete])
    resources("/projects", ProjectController, only: [:index, :show, :update, :delete])
    resources("/runners", RunnerController, only: [:index, :show, :delete, :update])
  end

  scope "/api/github", AlloyCi.Web.Api, as: :api do
    pipe_through([:api, :github])

    post("/handle_event", GithubEventController, :handle_event)
  end

  scope "/api/v4", AlloyCi.Web.Api, as: :runner_api do
    pipe_through([:api])

    scope "/runners" do
      post("/", RunnerEventController, :register, as: :register)
      delete("/", RunnerEventController, :delete, as: :delete)
      post("/verify", RunnerEventController, :verify, as: :verify)
    end

    scope "/jobs" do
      post("/request", BuildsEventController, :request, as: :verify)
      put("/:id", BuildsEventController, :update)
      post("/:id/artifacts/authorize", BuildsArtifactController, :authorize)
      post("/:id/artifacts", BuildsArtifactController, :create)
      get("/:id/artifacts", BuildsArtifactController, :show)
      patch("/:id/trace", BuildsEventController, :trace)
    end
  end

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end
end

lib/alloy_ci/web/views/shared_view.ex
defmodule AlloyCi.Web.SharedView do
  use AlloyCi.Web, :view
  alias AlloyCi.{Accounts, Notification, Notifications, User}
  import AlloyCi.Web.RunnerView, only: [global: 1, platform_icon: 1]

  @spec notification_badge(User.t()) :: <<>> | {:safe, [...]}
  def notification_badge(user) do
    case Notifications.count_for_user(user) do
      0 ->
        ""

      count ->
        content_tag :span, class: "badge badge-pill badge-danger" do
          count
        end
    end
  end

  @spec user_notifications(User.t()) :: [Notification.t()]
  def user_notifications(user) do
    Notifications.for_user(user)
  end
end

lib/alloy_ci/web/templates/shared/edit_runner_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div data-controller="tags">
    <div class="form-group">
      <div class="control-label m-b-1">
        <h5><strong>Tags</strong></h5>
      </div>
      <div class="input-group">
        <input type="text" data-action="keypress->tags#addTagOnEnter" data-target="tags.input" class="form-control">
        <span class="input-group-append">
          <%= content_tag :button, id: "add-tag", type: "button", class: "btn btn-primary",
                          data: [action: "tags#addTag", target: "tags.prototype", prototype: tag_element(f, :tags, "replace_me", "gen_new_id") |> safe_to_string] do %>
            Add
          <% end %>
        </span>
      </div>
      <span class="help-block">
        If you add tags to a runner, it will only pick up builds that have at least
        a subset of these tags, unless you allow the runner to run untagged builds.
        In that case it will prioritize builds with these tags, but will also be able
        to pick up any build job.
      </span>
      <%= error_tag f, :tags %>
    </div>

    <div class="control-label m-b-1">
      <h5><strong>Existing Tags</strong></h5>
    </div>
    <%= array_input f, :tags %>
    <div class="m-b-2">
      <hr>
      <span class="help-block">
        <strong>Hint:</strong>
        You can click on the <%= icon("close") %> icon to delete a tag. Don't forget
        to click <code>Submit</code> after editing for the changes to be saved.
      </span>
    </div>

    <div class="form-group">
      <div class="control-label m-b-1">
        <h5><strong>Run untagged builds?</strong></h5>
      </div>
      <div class="switch-button switch-button-yesno">
        <%= checkbox f, :run_untagged, class: "switch-input" %>
        <span>
          <label for="runner_run_untagged"></label>
        </span>
      </div>
      <%= error_tag f, :run_untagged %>
    </div>

    <div class="form-group">
      <%= submit "Submit", class: "btn btn-success" %>
    </div>
  </div>
<% end %>

lib/alloy_ci/web/templates/shared/navbar.html.eex
<nav class="navbar navbar-expand fixed-top aci-top-header">
  <div class="container-fluid">
    <div class="aci-navbar-header">
      <div class="page-title float-left">
        AlloyCI
      </div>
      <a href="#" class="aci-toggle-left-sidebar"><span class="text-white h3"><%= icon("bars") %></span></a>
    </div>

    <div class="aci-right-navbar">
      <ul class="nav navbar-nav float-right aci-user-nav">
        <li class="nav-item dropdown margin-right-imp">
          <a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <img src="<%= Accounts.gravatar_url(@current_user) %>" class="img-avatar" alt="<%= @current_user.email %>">
          </a>
          <div role="menu" class="dropdown-menu">     
            <div class="user-info">
              <div class="user-name"><%= @current_user.name %></div>
            </div>
            <%= link to: notification_path(@conn, :index), class: "dropdown-item" do %>
              <%= icon("bell fa-lg") %>
              Notifications
            <% end %>
            <%= link to: profile_path(@conn, :index), class: "dropdown-item" do %>
              <%= icon("user fa-lg") %>
              Profile
            <% end %>
            <div class="divider"></div>
            <%= link to: auth_path(@conn, :logout), method: :delete, class: "dropdown-item" do %>
              <%= icon("sign-out fa-lg") %>
              Logout
            <% end %>
            <!-- <%= if @current_user.is_admin do %>
              <div class="dropdown-header text-center">
                <strong>Settings</strong>
              </div>
              <a class="dropdown-item" href="#"><i class="fa fa-wrench"></i> Settings</a>
            <% end %> -->
          </div>
        </li>
      </ul>
      <ul class="nav navbar-nav float-right aci-icons-nav">
        <li class="nav-item hidden-md-down">
          <%= link to: notification_path(@conn, :index), class: "nav-link" do %>
            <%= icon("bell-o fa-lg") %>
            <%= notification_badge(@current_user) %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

lib/alloy_ci/web/templates/shared/runner.html.eex
<div class="col-sm-6 col-lg-4">
  <div class="card card-border-color card-border-color-warning">
    <div class="card-body project-card" data-url="<%= @show_path %>">
      <div class="btn-group pull-right">
        <%= link to: @delete_path, method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger p-a-0" do %>
          <%= icon("trash") %>
        <% end %>
      </div>
      <div class="h2 text-muted text-xs-right">
        <%= icon("cog") %>
      </div>
      <div class="m-b-0">
        <div class="h4 filter inline">
          <%= @runner.description %>
        </div>
        <small class="text-muted font-weight-bold pull-right">
          <%= @runner.version %>
        </small>
      </div>
      <div class="row">
        <div class="col-sm-6">
          <span class="text-muted h2">
            <%= platform_icon(@runner.platform) %>
          </span>
        </div>
        <div class="col-sm-6">
          <span class="text-muted h2">
            <span class="pull-right"><%= global(@runner) %></span>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>