lib/alloy_ci/web/router.ex
defmodule AlloyCi.Web.Router do
  use AlloyCi.Web, :router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  # This plug will look for a Guardian token in the session in the default location
  # Then it will attempt to load the resource found in the JWT.
  # If it doesn't find a JWT in the default location it doesn't do anything
  pipeline :browser_auth do
    plug(AlloyCi.Guardian.Pipeline)
  end

  # This pipeline is created for use within the admin namespace.
  # It looks for a valid token in the session - but in the 'admin' location of guardian
  # This keeps the session credentials separate for the main site, and the admin site
  # It's very possible that a user is logged into the main site but not the admin
  # or it could be that you're logged into both.
  # This does not conflict with the browser_auth pipeline.
  # If it doesn't find a JWT in the location it doesn't do anything
  pipeline :admin_browser_auth do
    plug(AlloyCi.Guardian.AdminPipeline)
  end

  # We need this pipeline to load the token when we're impersonating.
  # We don't want to load the resource though, just verify the token
  pipeline :impersonation_browser_auth do
    plug(Guardian.Plug.VerifySession, key: :admin)
  end

  pipeline :api do
    plug(:accepts, ["json", "text"])
  end

  pipeline :github do
    plug(AlloyCi.Plugs.GithubHeader)
  end

  # This pipeline if intended for API requests and looks for the JWT in the "Authentication" header
  # In this case, it should be prefixed with "Bearer" so that it's looking for
  # Authentication: Bearer <jwt>
  pipeline :api_auth do
    plug(Guardian.Plug.VerifyHeader, realm: "Bearer")
    plug(Guardian.Plug.LoadResource)
  end

  scope "/", AlloyCi.Web do
    # We pipe this through the browser_auth to fetch logged in people
    # We pipe this through the impersonation_browser_auth to know if we're impersonating
    # We don't just pipe it through admin_browser_auth because that also loads the resource
    pipe_through([:browser, :browser_auth, :impersonation_browser_auth])
    get("/", PublicController, :index)
    get("/register", PublicController, :register, as: :register)

    delete("/logout", AuthController, :logout)

    resources("/notifications", NotificationController, only: [:index, :delete, :update])
    post("/notifications/acknowledge_all", NotificationController, :acknowledge_all)
    post("/notifications/delete_all", NotificationController, :delete_all)

    resources("/profile", ProfileController, only: [:index, :update, :delete])
    delete("/profile/:auth_id/delete", ProfileController, :delete, as: :auth_delete)

    resources "/projects", ProjectController do
      resources("/pipelines", PipelineController, only: [:create, :delete, :show])

      resources("/builds", BuildController, only: [:show, :create, :update]) do
        get("/artifact", BuildController, :artifact, as: :artifact)
        post("/artifact/keep", BuildController, :keep_artifact, as: :keep_artifact)
      end

      resources("/badge/:ref", BadgeController, only: [:index])
    end

    resources("/runners", RunnerController, only: [:show, :delete, :update])

    resources("/tokens", TokenController, only: [:delete])
  end

  # This scope is the main authentication area for Ueberauth
  scope "/auth", AlloyCi.Web do
    # Use the default browser stack
    pipe_through([:browser, :browser_auth])

    get("/:provider", AuthController, :login)
    get("/:provider/callback", AuthController, :callback)
    post("/:provider/callback", AuthController, :callback)
  end

  # This scope is intended for admin users.
  # Normal users can only go to the login page
  scope "/admin", AlloyCi.Web.Admin, as: :admin do
    # Use the default browser stack
    pipe_through([:browser])

    get("/login", SessionController, :new, as: :login)
    get("/login/:provider", SessionController, :new)
    post("/auth/:provider/callback", SessionController, :callback)
  end

  scope "/admin", AlloyCi.Web.Admin, as: :admin do
    pipe_through([:browser, :admin_browser_auth])

    get("/logout", SessionController, :logout)
    delete("/logout", SessionController, :logout, as: :logout)
    post("/impersonate/:user_id", SessionController, :impersonate, as: :impersonation)
    delete("/impersonate", SessionController, :stop_impersonating)

    resources("/users", UserController, only: [:index, :show, :delete])
    resources("/projects", ProjectController, only: [:index, :show, :update, :delete])
    resources("/runners", RunnerController, only: [:index, :show, :delete, :update])
  end

  scope "/api/github", AlloyCi.Web.Api, as: :api do
    pipe_through([:api, :github])

    post("/handle_event", GithubEventController, :handle_event)
  end

  scope "/api/v4", AlloyCi.Web.Api, as: :runner_api do
    pipe_through([:api])

    scope "/runners" do
      post("/", RunnerEventController, :register, as: :register)
      delete("/", RunnerEventController, :delete, as: :delete)
      post("/verify", RunnerEventController, :verify, as: :verify)
    end

    scope "/jobs" do
      post("/request", BuildsEventController, :request, as: :verify)
      put("/:id", BuildsEventController, :update)
      post("/:id/artifacts/authorize", BuildsArtifactController, :authorize)
      post("/:id/artifacts", BuildsArtifactController, :create)
      get("/:id/artifacts", BuildsArtifactController, :show)
      patch("/:id/trace", BuildsEventController, :trace)
    end
  end

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end
end

lib/alloy_ci/web/views/admin/layout_view.ex
defmodule AlloyCi.Web.Admin.LayoutView do
  use AlloyCi.Web, :view
  alias AlloyCi.Accounts
end

lib/alloy_ci/web/views/layout_view.ex
defmodule AlloyCi.Web.LayoutView do
  use AlloyCi.Web, :view
  alias AlloyCi.{Accounts, Projects}
  import AlloyCi.Web.ProjectView, only: [ref_icon: 1]
  import AlloyCi.Builds, only: [clean_ref: 1]

  def can_manage?(pipeline, user) do
    Projects.can_manage?(pipeline.project_id, user)
  end
end

lib/alloy_ci/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Continuous Integration set free.">
  <meta name="author" content="Alloy CI">
  <meta name="keyword" content="Continuous Integration,CI,CD,GitHub,GitLab">
  <link rel="shortcut icon" href="/favicon.ico">

  <title>AlloyCI</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
</head>

<body>
  <div class="aci-wrapper aci-color-header aci-fixed-sidebar aci-collapsible-sidebar">
    <%= render AlloyCi.Web.SharedView, "navbar.html", current_user: @current_user, conn: @conn %>
    <%= render "sidebar.html", current_user: @current_user, conn: @conn, projects: Projects.latest(@current_user) %>

    <div class="aci-content m-b-1">
      <%= render_flash(@conn, :info) %>
      <%= render_flash(@conn, :error) %>
      <%= render_flash(@conn, :success) %>

      <!-- Main content -->
      <%= @inner_content %>
    </div>

    <footer class="app-footer">
      <span class="float-right m-r-3"><a href="https://alloy-ci.com">AlloyCI</a> © <%= Timex.now.year %> Insomniware,
        LLC.</span>
    </footer>
  </div>
  <script>
    window.userToken = "<%= Accounts.get_valid_auth_token(@current_user) %>";
  </script>
  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</body>

</html>

lib/alloy_ci/web/templates/layout/email_layout.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Continuous Integration set free.">
    <meta name="author" content="Alloy CI">
    <meta name="keyword" content="Continuous Integration,CI,CD,GitHub,GitLab">
    <link rel="stylesheet" href="<%= static_url(AlloyCi.Web.Endpoint, "/css/app.css") %>">
  </head>
  <body>
    <%= @inner_content %>
  </body>
</html>

lib/alloy_ci/web/templates/layout/login_layout.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Continuous Integration set free.">
  <meta name="author" content="Alloy CI">
  <meta name="keyword" content="Continuous Integration,CI,CD,GitHub,GitLab">
  <link rel="shortcut icon" href="/favicon.ico">

  <title>AlloyCI | Log in</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
</head>

<body class="aci-splash-screen">
  <div class="aci-wrapper aci-login">
    <div class="aci-content">
      <%= render_flash(@conn, :info) %>
      <%= render_flash(@conn, :error) %>
      <%= render_flash(@conn, :success) %>

      <div class="main-content container-fluid">
        <div class="splash-container">
          <div class="card card-border-color card-border-color-primary">
            <div class="card-header">
              <h2 class="page-title">AlloyCI<h2>
                  <span class="splash-description">
                    Please enter your user information to
                    <%= if @current_user do %>
                    connect your account
                    <% else %>
                    login
                    <% end %>
                  </span>
            </div>
            <div class="card-body">
              <%= @inner_content %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</body>

</html>

lib/alloy_ci/web/templates/layout/pipeline_info.html.eex
<div class="page-head">
  <h2 class="page-head-title">
    <%= @pipeline.project.owner %>/<%= link @pipeline.project.name, to: project_path(@conn, :show, @pipeline.project_id), class: "pipeline-link" %>
  </h2>
  <nav aria-label="breadcrumb" role="navigation">
    <!-- Breadcrumb -->
    <ol class="breadcrumb page-head-nav">
      <li class="breadcrumb-item">
        <%= ref_icon(@pipeline.ref) %>
        <%= clean_ref(@pipeline.ref) %>
      </li>
      <li class="breadcrumb-item">
        <%= icon("github") %>
        <%= sha_link(@pipeline) %>
      </li>
      <li class="breadcrumb-item">
        <%= icon("book") %>
        <%= pretty_commit(@pipeline.commit["message"]) %>
      </li>
      <%= if @pipeline.commit["pr_commit_message"] do %>
        <li class="breadcrumb-item">
          <%= icon("code-fork") %>
          <%= @pipeline.commit["pr_commit_message"] %>
        </li>
      <% end %>
      <li class="breadcrumb-item">
        <%= icon("tasks") %>
        <%= String.capitalize(@pipeline.status) %>
        <%= status_icon(@pipeline.status) %>
      </li>
    </ol>
  </nav>
</div>

lib/alloy_ci/web/templates/layout/pipeline_layout.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Continuous Integration set free.">
  <meta name="author" content="Alloy CI">
  <meta name="keyword" content="Continuous Integration,CI,CD,GitHub,GitLab">
  <link rel="shortcut icon" href="/favicon.ico">

  <title>AlloyCI</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
</head>

<body>
  <div class="aci-wrapper aci-color-header aci-fixed-sidebar aci-collapsible-sidebar">
    <%= render AlloyCi.Web.SharedView, "navbar.html", current_user: @current_user, conn: @conn %>
    <%= render "sidebar.html", current_user: @current_user, conn: @conn, projects: Projects.latest(@current_user) %>

    <div class="aci-content m-b-1">
      <%= render_flash(@conn, :info) %>
      <%= render_flash(@conn, :error) %>
      <%= render_flash(@conn, :success) %>
      <%= render "pipeline_info.html", conn: @conn, pipeline: @pipeline %>
      <!-- Main content -->
      <div class="main-content container-fluid">
        <%= @inner_content %>
      </div>
    </div>

    <footer class="app-footer">
      <span class="float-right m-r-3"><a href="https://alloy-ci.com">AlloyCI</a> © <%= Timex.now.year %> Insomniware,
        LLC.</span>
    </footer>
  </div>

  <script>
    window.userToken = "<%= Accounts.get_valid_auth_token(@current_user) %>";
  </script>
  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</body>

</html>

lib/alloy_ci/web/templates/layout/pipeline_sidebar.html.eex
<div data-controller="builds" class="sidebar">
  <nav class="sidebar-nav">
    <ul class="nav">
      <li class="nav-item">
        <%= link to: project_path(@conn, :show, @pipeline.project_id), class: "nav-link" do %>
          <%= icon("code-fork") %> Pipelines
        <% end %>
      </li>
      <li class="nav-title">Stages</li>
      <%= for stage <- @builds do %>
        <%= for {name, builds} <- stage do %>
          <li class="nav-subtitle"><%= name %></li>
          <%= for build <- builds do %>
            <li class="nav-item">
              <a class="nav-link"
                 data-action="builds#fetchData"
                 data-build-url="<%= project_build_path(@conn, :show, build.project_id, build.id) %>"
                 data-id="<%= build.id %>" data-name="<%= build.name %>" href="#">
                 <%= icon("terminal") %> <%= build.name %>
                 <span class="float-right"><%= status_icon(build.status) %></span>
             </a>
            </li>
          <% end %>
        <% end %>
      <% end %>
      <%= if can_manage?(@pipeline, @current_user) do %>
        <li class="nav-title">Actions</li>
        <li class="nav-item">
          <%= case @pipeline.status do %>
            <% s when s in ~w(pending running) -> %>
              <%= link to: project_pipeline_path(@conn, :delete, @pipeline.project_id, @pipeline), method: :delete, class: "nav-link" do %>
                <%= icon("ban") %> Cancel pipeline
              <% end %>
            <% s when s in ~w(failed cancelled) -> %>
              <%= link to: project_pipeline_path(@conn, :create, @pipeline.project_id, %{id: @pipeline.id}), method: :post, class: "nav-link" do %>
                <%= icon("refresh") %> Restart pipeline
              <% end %>
            <% _ -> %>
              <a class="nav-link">
                <%= icon("heart") %> All good here
              </a>
          <% end %>
        </li>
      <% end %>
    </ul>
  </nav>
</div>

lib/alloy_ci/web/templates/layout/public_layout.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Continuous Integration set free.">
  <meta name="author" content="Alloy CI">
  <meta name="keyword" content="Continuous Integration,CI,CD,GitHub,GitLab,Deployment,Delivery">
  <link rel="shortcut icon" href="/favicon.ico">
  <title>AlloyCI</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/kit.css") %>">
</head>

<body class="index" id="page-top">

  <section class="cover-5 text-center">
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-custom navbar-light">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="/images/logo.png" class="img-avatar" width="25%" alt="logo">
          AlloyCI
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
          data-target="#navbarToggler-5" aria-controls="navbarToggler-5" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse pull-xs-right justify-content-end" id="navbarToggler-5">
          <ul class="navbar-nav mt-2 mt-md-0">
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/AlloyCI/alloy_ci/tree/master/doc">Documentation</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#features">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#download">Download</a>
            </li>
            <li class="nav-item">
              <%= if @current_user do %>
              <%= link "Projects", to: project_path(@conn, :index), class: "main-link btn btn-outline-success btn-outline" %>
              <% else %>
              <%= link "Log in", to: auth_path(@conn, :login, "identity"), class: "main-link btn btn-outline-success btn-outline" %>
              <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="cover-container pb-5 ">
      <div class="cover-inner container">
        <p class="lead">[Continuous] |> Integration |> Deployment |> Delivery</p>
        <div class="divider"></div>
        <h1 class="jumbotron-heading">Welcome to <em><strong>AlloyCI</strong></em></h1>
        <div class="row">
          <div class="offset-md-4 col-md-4 mt-5">
            <a href="#download" class="btn btn-lg btn-success pill-btn">Get Started</a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <%= @inner_content %>

  <!-- Footer -->
  <footer class="footer-3">
    <div class="container">
      <div class="row">
        <div class="col-md-6 text-center text-md-left mt-2 mb-3 pt-1">
          <p>Copyright &copy; <%= Timex.now.year %> Insomniware, LLC</p>
        </div>
        <div class="col-md-6 text-center text-md-right mb-4">
          <ul class="social">
            <li><a href="https://twitter.com/AlloyCI" title="Twitter" class="fa fa-twitter"></a></li>
            <li><a href="https://github.com/AlloyCI" title="GitHub" class="fa fa-github"></a></li>
            <div class="clear"></div>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  <!-- Bootstrap core JavaScript -->
  <script>
    window.userToken = "1";
  </script>
  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</body>

</html>

lib/alloy_ci/web/templates/layout/register_layout.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Continuous Integration set free.">
  <meta name="author" content="Alloy CI">
  <meta name="keyword" content="Continuous Integration,CI,CD,GitHub,GitLab">
  <link rel="shortcut icon" href="/favicon.ico">

  <title>AlloyCI | Register</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
</head>

<body class="aci-splash-screen">
  <div class="aci-wrapper aci-login aci-signup">
    <div class="aci-content">
      <%= render_flash(@conn, :info) %>
      <%= render_flash(@conn, :error) %>
      <%= render_flash(@conn, :success) %>

      <div class="main-content container-fluid">
        <div class="splash-container">
          <div class="card card-border-color card-border-color-primary">
            <div class="card-header">
              <h2 class="page-title">AlloyCI<h2>
                  <span class="splash-description">
                    Please enter your user information to
                    <%= if @current_user do %>
                    connect your account
                    <% else %>
                    register
                    <% end %>
                  </span>
            </div>
            <div class="card-body">
              <%= @inner_content %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</body>

</html>

lib/alloy_ci/web/templates/layout/sidebar.html.eex
<div class="aci-left-sidebar">
  <div class="left-sidebar-wrapper">
    <div class="left-sidebar-spacer">
      <div class="left-sidebar-scroll">
        <div class="left-sidebar-content">
          <ul class="sidebar-elements">
            <li class="divider">
              Home
            </li>
            <li>
              <%= link to: project_path(@conn, :index), class: "nav-link" do %>
                <%= icon("home") %>
                My projects
              <% end %>  
            </li>

            <%= if @current_user.is_admin do %>
              <li>
                <%= link to: admin_user_path(@conn, :index), class: "nav-link" do %>
                  <%= icon("cogs") %>
                  Admin
                <% end %>  
              </li>
              <!-- <li class="nav-item px-1">
                <a class="nav-link" href="#">Settings</a>
              </li> -->
            <% end %>
            <li class="divider">
              Recent projects
            </li>
            <%= for project <- @projects do %>
              <li>
                <%= link to: project_path(@conn, :show, project.id), class: "nav-link" do %>
                  <%= icon("cube") %>
                  <%= project.name %>
                <% end %>
              </li>
            <% end %>
            <li class="divider">
              Add
            </li>
            <li>
              <%= link to: project_path(@conn, :new), class: "nav-link" do %>
                <%= icon("plus") %>
                New Project
              <% end %>
            </li>
            <li class="divider"></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>