lib/alloy_ci/web/router.ex
defmodule AlloyCi.Web.Router do
  use AlloyCi.Web, :router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  # This plug will look for a Guardian token in the session in the default location
  # Then it will attempt to load the resource found in the JWT.
  # If it doesn't find a JWT in the default location it doesn't do anything
  pipeline :browser_auth do
    plug(AlloyCi.Guardian.Pipeline)
  end

  # This pipeline is created for use within the admin namespace.
  # It looks for a valid token in the session - but in the 'admin' location of guardian
  # This keeps the session credentials separate for the main site, and the admin site
  # It's very possible that a user is logged into the main site but not the admin
  # or it could be that you're logged into both.
  # This does not conflict with the browser_auth pipeline.
  # If it doesn't find a JWT in the location it doesn't do anything
  pipeline :admin_browser_auth do
    plug(AlloyCi.Guardian.AdminPipeline)
  end

  # We need this pipeline to load the token when we're impersonating.
  # We don't want to load the resource though, just verify the token
  pipeline :impersonation_browser_auth do
    plug(Guardian.Plug.VerifySession, key: :admin)
  end

  pipeline :api do
    plug(:accepts, ["json", "text"])
  end

  pipeline :github do
    plug(AlloyCi.Plugs.GithubHeader)
  end

  # This pipeline if intended for API requests and looks for the JWT in the "Authentication" header
  # In this case, it should be prefixed with "Bearer" so that it's looking for
  # Authentication: Bearer <jwt>
  pipeline :api_auth do
    plug(Guardian.Plug.VerifyHeader, realm: "Bearer")
    plug(Guardian.Plug.LoadResource)
  end

  scope "/", AlloyCi.Web do
    # We pipe this through the browser_auth to fetch logged in people
    # We pipe this through the impersonation_browser_auth to know if we're impersonating
    # We don't just pipe it through admin_browser_auth because that also loads the resource
    pipe_through([:browser, :browser_auth, :impersonation_browser_auth])
    get("/", PublicController, :index)
    get("/register", PublicController, :register, as: :register)

    delete("/logout", AuthController, :logout)

    resources("/notifications", NotificationController, only: [:index, :delete, :update])
    post("/notifications/acknowledge_all", NotificationController, :acknowledge_all)
    post("/notifications/delete_all", NotificationController, :delete_all)

    resources("/profile", ProfileController, only: [:index, :update, :delete])
    delete("/profile/:auth_id/delete", ProfileController, :delete, as: :auth_delete)

    resources "/projects", ProjectController do
      resources("/pipelines", PipelineController, only: [:create, :delete, :show])

      resources("/builds", BuildController, only: [:show, :create, :update]) do
        get("/artifact", BuildController, :artifact, as: :artifact)
        post("/artifact/keep", BuildController, :keep_artifact, as: :keep_artifact)
      end

      resources("/badge/:ref", BadgeController, only: [:index])
    end

    resources("/runners", RunnerController, only: [:show, :delete, :update])

    resources("/tokens", TokenController, only: [:delete])
  end

  # This scope is the main authentication area for Ueberauth
  scope "/auth", AlloyCi.Web do
    # Use the default browser stack
    pipe_through([:browser, :browser_auth])

    get("/:provider", AuthController, :login)
    get("/:provider/callback", AuthController, :callback)
    post("/:provider/callback", AuthController, :callback)
  end

  # This scope is intended for admin users.
  # Normal users can only go to the login page
  scope "/admin", AlloyCi.Web.Admin, as: :admin do
    # Use the default browser stack
    pipe_through([:browser])

    get("/login", SessionController, :new, as: :login)
    get("/login/:provider", SessionController, :new)
    post("/auth/:provider/callback", SessionController, :callback)
  end

  scope "/admin", AlloyCi.Web.Admin, as: :admin do
    pipe_through([:browser, :admin_browser_auth])

    get("/logout", SessionController, :logout)
    delete("/logout", SessionController, :logout, as: :logout)
    post("/impersonate/:user_id", SessionController, :impersonate, as: :impersonation)
    delete("/impersonate", SessionController, :stop_impersonating)

    resources("/users", UserController, only: [:index, :show, :delete])
    resources("/projects", ProjectController, only: [:index, :show, :update, :delete])
    resources("/runners", RunnerController, only: [:index, :show, :delete, :update])
  end

  scope "/api/github", AlloyCi.Web.Api, as: :api do
    pipe_through([:api, :github])

    post("/handle_event", GithubEventController, :handle_event)
  end

  scope "/api/v4", AlloyCi.Web.Api, as: :runner_api do
    pipe_through([:api])

    scope "/runners" do
      post("/", RunnerEventController, :register, as: :register)
      delete("/", RunnerEventController, :delete, as: :delete)
      post("/verify", RunnerEventController, :verify, as: :verify)
    end

    scope "/jobs" do
      post("/request", BuildsEventController, :request, as: :verify)
      put("/:id", BuildsEventController, :update)
      post("/:id/artifacts/authorize", BuildsArtifactController, :authorize)
      post("/:id/artifacts", BuildsArtifactController, :create)
      get("/:id/artifacts", BuildsArtifactController, :show)
      patch("/:id/trace", BuildsEventController, :trace)
    end
  end

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end
end

lib/alloy_ci/web/controllers/admin/project_controller.ex
defmodule AlloyCi.Web.Admin.ProjectController do
  use AlloyCi.Web, :admin_controller

  alias AlloyCi.{Project, Projects}

  plug(EnsureAuthenticated, handler: AlloyCi.Web.Admin.UserController, key: :admin)

  def index(conn, params, current_user, _) do
    {projects, kerosene} = Projects.all(params)
    render(conn, "index.html", current_user: current_user, kerosene: kerosene, projects: projects)
  end

  def show(conn, %{"id" => id}, current_user, _) do
    project = Projects.get(id)
    changeset = Project.changeset(project)
    render(conn, "show.html", current_user: current_user, project: project, changeset: changeset)
  end

  def update(conn, %{"id" => id, "project" => project_params}, current_user, _claims) do
    project = Projects.get(id)

    case Projects.update(project, project_params) do
      {:ok, project} ->
        conn
        |> put_flash(:info, "Project updated successfully.")
        |> redirect(to: admin_project_path(conn, :show, project))

      {:error, changeset} ->
        render(
          conn,
          "show.html",
          project: project,
          changeset: changeset,
          current_user: current_user
        )
    end
  end

  def delete(conn, %{"id" => id}, _, _) do
    {:ok, _} = Projects.delete_by(id)

    conn
    |> put_flash(:info, "Project was deleted successfully")
    |> redirect(to: admin_project_path(conn, :index))
  end
end

lib/alloy_ci/web/controllers/project_controller.ex
defmodule AlloyCi.Web.ProjectController do
  use AlloyCi.Web, :controller
  alias AlloyCi.{Project, Projects, Queuer, Workers}
  import Phoenix.HTML.Link
  import AlloyCi.Web.ProjectView, only: [app_url: 0]

  plug(EnsureAuthenticated, handler: AlloyCi.Web.AuthController, typ: "access")

  def index(conn, params, current_user, _claims) do
    {projects, kerosene} = Projects.paginated_for(current_user, params)
    render(conn, "index.html", kerosene: kerosene, projects: projects, current_user: current_user)
  end

  def new(conn, _params, current_user, _claims) do
    Queuer.push(Workers.FetchReposWorker, {current_user.id, get_csrf_token()})

    render(conn, "new.html", current_user: current_user)
  end

  def create(conn, %{"project" => project_params}, current_user, _claims) do
    case Projects.create_project(project_params, current_user) do
      {:ok, project} ->
        conn
        |> put_flash(:info, "Project created successfully.")
        |> redirect(to: project_path(conn, :show, project))

      {:missing_installation, _} ->
        conn
        |> put_flash(:error, [
          "This project's organization is not configured to use AlloyCI. Please go to the ",
          link("GitHub Integration", to: app_url(), target: "_blank", class: "flash-link"),
          " page to configure AlloyCI for this organization."
        ])
        |> redirect(to: project_path(conn, :index))

      {:missing_config, _} ->
        conn
        |> put_flash(:error, [
          "The selected project doesn't have an .alloy-ci.yml config file. Please see the ",
          link(
            "documentation",
            to: "https://github.com/AlloyCI/alloy_ci/tree/master/doc",
            target: "_blank",
            class: "flash-link"
          ),
          " for information on how to add one."
        ])
        |> redirect(to: project_path(conn, :index))

      {:error, _} ->
        conn
        |> put_flash(:error, "There was an error creating your project. Please try again.")
        |> redirect(to: project_path(conn, :index))
    end
  end

  def show(conn, %{"id" => id} = params, current_user, _claims) do
    case Projects.show_by(id, current_user, %{"page" => params["page"]}) do
      {:ok, {project, pipelines, kerosene}} ->
        render(
          conn,
          "show.html",
          project: project,
          pipelines: pipelines,
          kerosene: kerosene,
          current_user: current_user
        )

      {:error, nil} ->
        conn
        |> put_flash(:info, "Project not found")
        |> redirect(to: project_path(conn, :index))
    end
  end

  def edit(conn, %{"id" => id}, current_user, _claims) do
    with {:ok, project} <- Projects.get_by(id, current_user, preload: :runners) do
      changeset = Project.changeset(project)

      render(
        conn,
        "edit.html",
        project: project,
        changeset: changeset,
        current_user: current_user
      )
    else
      {:error, nil} ->
        conn
        |> put_flash(:info, "Project not found")
        |> redirect(to: project_path(conn, :index))
    end
  end

  def update(conn, %{"id" => id, "project" => project_params}, current_user, _claims) do
    with {:ok, project} <- Projects.get_by(id, current_user, preload: :runners) do
      case Projects.update(project, project_params) do
        {:ok, project} ->
          conn
          |> put_flash(:info, "Project updated successfully.")
          |> redirect(to: project_path(conn, :edit, project))

        {:error, changeset} ->
          render(
            conn,
            "edit.html",
            project: project,
            changeset: changeset,
            current_user: current_user
          )
      end
    else
      {:error, nil} ->
        conn
        |> put_flash(:info, "Project not found")
        |> redirect(to: project_path(conn, :index))
    end
  end

  def delete(conn, %{"id" => id}, current_user, _claims) do
    with {:ok, _} <- Projects.delete_by(id, current_user) do
      conn
      |> put_flash(:info, "Project deleted successfully.")
      |> redirect(to: project_path(conn, :index))
    else
      {:error, nil} ->
        conn
        |> put_flash(:info, "Project not found")
        |> redirect(to: project_path(conn, :index))
    end
  end
end

lib/alloy_ci/web/views/admin/project_view.ex
defmodule AlloyCi.Web.Admin.ProjectView do
  use AlloyCi.Web, :view
  alias AlloyCi.Projects
  import Kerosene.HTML
  import AlloyCi.Web.ProjectView, only: [builds_chart: 1]
end

lib/alloy_ci/web/views/project_view.ex
defmodule AlloyCi.Web.ProjectView do
  use AlloyCi.Web, :view
  alias AlloyCi.{Accounts, Project, Projects, User}
  import Kerosene.HTML
  import AlloyCi.Builds, only: [clean_ref: 1, ref_type: 1]
  import AlloyCi.Web.RunnerView, only: [platform_icon: 1, global_runners: 0]

  @github_api Application.get_env(:alloy_ci, :github_api)

  @spec app_url() :: binary()
  def app_url do
    Application.get_env(:alloy_ci, :app_url)
  end

  @spec reauth_url() :: binary()
  def reauth_url do
    @github_api.app_auth_url()
  end

  @spec builds_chart(Project.t()) ::
          binary()
          | maybe_improper_list(
              binary() | maybe_improper_list(any(), binary() | []) | byte(),
              binary() | []
            )
  def builds_chart(project) do
    project
    |> Chartable.builds_chart()
    |> Poison.encode!()
  end

  @spec has_github_auth(User.t()) :: boolean()
  def has_github_auth(user) do
    case Accounts.github_auth(user) do
      nil -> false
      _ -> true
    end
  end

  @spec ref_icon(binary()) :: {:safe, binary()}
  def ref_icon(ref) do
    ref
    |> ref_type()
    |> render_icon()
  end

  @spec tags(any()) :: <<_::120>> | [any()]
  def tags(nil) do
    "No tags defined"
  end

  def tags(tags) do
    tags
    |> Enum.map(&tag_element/1)
  end

  ###################
  # Private functions
  ###################
  defp render_icon("branches") do
    {:safe, "<i class='fa fa-random'></i>"}
  end

  defp render_icon("tags") do
    {:safe, "<i class='fa fa-tags'></i>"}
  end

  defp render_icon("forks") do
    {:safe, "<i class='fa fa-code-fork'></i>"}
  end

  defp tag_element(value) do
    content_tag :div, class: "inline m-r-1" do
      [
        content_tag :button,
          type: "button",
          class: "btn btn-sm btn-info text-white m-t-1" do
          [value <> " "]
        end
      ]
    end
  end
end

lib/alloy_ci/web/templates/project/edit.html.eex
<div class="page-head">
  <h2 class="page-head-title">
    <%= @project.owner %>/<%= @project.name %>
  </h2>
</div>

<div class="main-content container-fluid">
   <div class="row">
    <div class="col-sm-12 col-xl-5">
      <div class="card card-border-color card-border-color-dark">
        <div class="card-header">
          Project Settings
        </div>
        <div class="card-body">
          <%= render "edit_form.html", changeset: @changeset, action: project_path(@conn, :update, @project), project: @project, conn: @conn %>                    
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-xl-7">
      <div class="row">
        <div class="col-sm-12">
          <div class="card card-border-color card-border-color-dark">
            <div class="card-header">
              Build Status
            </div>
            <div class="card-body">
              <p>
                If you would like to add a build status badge to the README of your
                project, you can use the following snippets. The badge will appear
                like this:
              </p>
              <img alt="build status" src='<%= project_badge_path(@conn, :index, @project, "master") %>'></a>
              <hr>

              <strong>Markdown</strong>
              <pre class="code highlight"><code>![build status](<%= project_badge_url(@conn, :index, @project, "master") %>)</code></pre>
              <hr>

              <strong>HTML</strong>
              <pre class="code highlight"><code>&lt;img alt="build status" src="<%= project_badge_url(@conn, :index, @project, "master") %>"/&gt;</code></pre>
            </div>
          </div>
        </div>
        <div class="col-sm-12">
          <div data-controller="charts" class="card card-border-color card-border-color-dark">
            <div class="card-header">
              Build Statistics
            </div>
            <div class="card-body">
              <canvas class="chart" data-set="<%= builds_chart(@project) %>"
                      data-title="Project's Build statistics" data-axis="Number of processed builds"
                      data-label="Week of" data-type="line"></canvas>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-xl-5">
      <div class="card card-border-color card-border-color-dark">
        <div class="card-header">
          Project Specific Runners
        </div>
        <div class="card-body">
          <h5>Runners allow you to execute and build your pipelines.</h5>
          <hr>
          <p>To add a project specific runner to AlloyCI, please follow these steps:</p>
          <div class="m-b-2">
            <b>Download and install the AlloyCI Runner for your operating system</b>
            <hr>
            Please follow the <a href="https://github.com/AlloyCI/alloy-runner/tree/master/docs/install" target="_blank">documentation</a>
            for instructions on how to install the AlloyCI Runner for your
            operating system.
          </div>
          <div class="m-b-2">
            <b>Register the runner</b>
            <hr>
            <p>
              Once installed, run <code>alloy-runner register</code> to start the
              registration process
            </p>
            <p>
              The registration wizard will ask you for information about the
              coordinator. This is the AlloyCI server.
              <ul>
                <li>As coordinator URL, enter <code><%= server_url() %></code></li>
                <li>As token, enter <code><%= @project.token %></code></li>
                <li>
                  The description can be anything that will help you recognize
                  this runner.
                </li>
                <li>
                  If you would like this runner to process only certain builds,
                  you can enter tags that will restrict the kind of builds this
                  runner is able to pick up, e.g. <code>elixir</code>,
                  <code>ios</code>, etc. You should separate the tags with a
                  comma <code>,</code> and ONLY with a comma.
                </li>
                <li>
                  If you add tags to the runner, the wizard will ask you if you
                  would like to run untagged builds as well. The runner will prioritize
                  builds that have a sub-set of its tags, but will also be able
                  to pick up any builds.
                </li>
                <li>
                  The wizard will also ask you if you want to lock the runner
                  to a specific project. This doesn't apply for AlloyCI. Project
                  specific runners will only process the project's builds.
                </li>
                <li>
                  Finally, the wizard will ask you to select the executor type.
                  You can choose between
                  <code>
                    docker-ssh+machine, docker, shell, docker+machine,
                    virtualbox, kubernetes, docker-ssh, parallels, ssh
                  </code>
                  <br>
                  For more information about the different executors, please have
                  a look at the documentation <a href="https://github.com/AlloyCI/alloy-runner/tree/master/docs/executors" target="_blank">here.</a>
                </li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-xl-7">
      <div class="row">
        <div class="col-sm-12">
          <div class="card card-border-color card-border-color-dark">
            <div class="card-header">
              Runners Registered for this Project
            </div>
            <div class="card-body">
              <%= case @project.runners do %>
                <% [] -> %>
                  <div class="centered">
                    <div class="row">
                      <div class="col-6 offset-3 allign-center">
                        <h4>
                          <%= icon("gears", "fa-3x") %>
                        </h4>
                        <br>
                        <h4>
                          There are no registred runners for this project. Add one now!
                        </h4>
                      </div>
                    </div>
                  </div>
                <% runners -> %>
                  <div class="row">
                    <%= for runner <- runners do %>
                      <%= render AlloyCi.Web.SharedView, "runner.html", 
                                runner: runner, delete_path: runner_path(@conn, :delete, runner), show_path: runner_path(@conn, :show, runner) %>
                    <% end %>
                  </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-sm-12">
          <div class="card card-border-color card-border-color-dark">
            <div class="card-header">
              Available Global Runners
            </div>
            <div class="card-body">
              <%= case global_runners() do %>
                <% [] -> %>
                  <div class="centered">
                    <div class="row">
                      <div class="col-6 offset-3 allign-center">
                        <h4>
                          <%= icon("gears", "fa-3x") %>
                        </h4>
                        <br>
                        <h4>
                          There are no available global runners. Ask your administrator to add one.
                        </h4>
                      </div>
                    </div>
                  </div>
                <% runners -> %>
                  <div class="row">
                    <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Platform</th>
                          <th>Tags</th>
                        </tr>
                      </thead>
                      <tbody>
                        <%= for runner <- runners do %>
                          <tr>
                            <td><%= runner.description %></td>
                            <td class="h2"><%= platform_icon(runner.platform) %></td>
                            <td><%= runner.tags |> tags() %></td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

lib/alloy_ci/web/templates/project/edit_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div data-controller="tags">
    <div class="form-group">
      <div class="control-label m-b-1">
        <h5><strong>Tags</strong></h5>
      </div>
      <div class="input-group">
        <input data-action="keypress->tags#addTagOnEnter" data-target="tags.input" type="text" class="form-control">
        <span class="input-group-append">
          <%= content_tag :button, type: "button", id: "add-tag", class: "btn btn-primary", 
                          data: [action: "tags#addTag", target: "tags.prototype", prototype: tag_element(f, :tags, "replace_me", "gen_new_id") |> safe_to_string] do %>
            Add
          <% end %>
        </span>
      </div>
      <span class="help-block">
        If you add tags to a project, all the build jobs created for this project
        that don't define their own tags in the <code>.alloy-ci.yml</code> file
        will, by default, receive these tags
      </span>
      <%= error_tag f, :tags %>
    </div>

    <div class="control-label m-b-1">
      <h5><strong>Existing Tags</strong></h5>
    </div>
    <%= array_input f, :tags %>
    <div class="m-b-2">
      <hr>
      <span class="help-block">
        <strong>Hint:</strong>
        You can click on the <%= icon("close") %> icon to delete a tag. Don't forget
        to click <code>Submit</code> after editing for the changes to be saved.
      </span>
    </div>

    <div class="form-group">
      <div class="control-label m-b-1">
        <h5><strong>Private project?</strong></h5>
      </div>
      <div class="switch-button switch-button-yesno">
        <%= checkbox f, :private, class: "switch-input" %>
        <span>
          <label for="project_private"></label>
        </span>
      </div>
      <%= error_tag f, :private %>
    </div>

    <div data-controller="projects" class="form-group">
      <div class="control-label m-b-1">
        <h5><strong>Secret Variables</strong></h5>
      </div>
      <%= textarea f, :secret_variables, class: "form-control", placeholder: "Save your secret variables in JSON format, e.g\n {\"AWS_SECRET\":\"super_long_secret\"}" %>
    </div>

    <div class="form-group">
      <%= submit "Submit", class: "btn btn-success" %>
      <%= link to: project_path(@conn, :delete, @project), method: :delete, data: [confirm: "Are you sure?"], class: "inline btn btn-danger p-a-0" do %>
        Delete Project
      <% end %>  
      <%= link "Back", to: project_path(@conn, :show, @project), class: "inline btn btn-secondary p-a-0" %>
    </div>
  </div>
<% end %>

lib/alloy_ci/web/templates/project/index.html.eex
<div class="page-head">
  <h2 class="page-head-title">
    Your projects
  </h2>
</div>

<%= if Enum.empty?(@projects) do %>
  <%= if has_github_auth(@current_user) do %>
    <div class="main-content container-fluid">
      <div class="super-center empty-state">
        <div class="row">
          <div class="col-6 offset-4 allign-center">
            <h3>
              <%= icon("space-shuttle", "fa-4x") %>
            </h3>
            <br>
            <h2>
              You haven't added any projects yet!
            </h2>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="main-content container-fluid">
      <div class="row">
        <div class="col-md-6 offset-md-3 col-sm-10 offset-sm-1">
          <div class="card card-border-color card-border-color-danger">
            <div class="card-body">
              <div class="h1 text-sm-right m-b-2">
                <%= icon("exclamation-triangle") %>
              </div>
              <div class="h4 m-b-0">
                <p>
                  You need to add your GitHub account in order to be able to use
                  AlloyCI.
                </p>
                <p>
                  <%= link to: auth_path(@conn, :login, "github"), class: "btn btn-secondary" do %>
                    <%= icon("github") %>
                    Link GitHub account
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="main-content container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <div class="card card-border-color card-border-color-dark">
          <div class="card-header"></div>
          <div class="card-body">
            <div data-controller="repos" class="input-group m-b-2">
              <div class="input-group-prepend">
                <span class="input-group-text"><%= icon("search") %></i></span>
              </div>
              <input data-action="keyup->repos#filter" data-target="repos.input" type="text" class="form-control" placeholder="Filter...">
            </div>
            <div class="row">
              <% statuses = Projects.last_statuses(@projects) %>
              <%= for project <- @projects do %>
                <% status = statuses |> Map.get(project.id, "unknown") %>
                <div class="col-sm-6 col-lg-4 col-xl-3" id="card-<%= project.repo_id %>">
                  <div class="card <%= card_status(status)%>">
                    <div class="card-body project-card" data-url="<%= project_path(@conn, :show, project) %>">
                      <div class="btn-group pull-right p-t-12">
                        <%= link to: project_path(@conn, :edit, project), class: "btn btn-warning text-white p-a-0" do %>
                          <%= icon("cogs") %>
                        <% end %>
                      </div>
                      <div class="h2 text-xs-right">
                        <%= icon("archive") %>
                      </div>
                      <div class="h4 m-b-0">
                        <div class="filter inline" data-id="<%= project.repo_id %>">
                          <%= project.name %>
                        </div>
                        <small><%= privacy_icon(project.private) %></small>
                      </div>
                      <span class="text-uppercase m-b-2">
                        <%= project.owner %>
                      </span>
                      <span class="text-uppercase pull-right">
                        Last status: <%= String.capitalize(status) %>
                      </span>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
            <%= paginate @conn, @kerosene, next_label: "»", previous_label: "«" %>
            <%= link to: project_path(@conn, :new), class: "btn btn-secondary" do %>
              <%= icon("plus") %>
              New project
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

lib/alloy_ci/web/templates/project/new.html.eex
<div class="page-head">
  <h2 class="page-head-title">
    Add your repos to AlloyCI
  </h2>
</div>

<div class="main-content container-fluid">
  <div data-controller="repos" data-repos-user="<%= @current_user.id %>">
    <div class="card card-border-color card-border-color-dark">
      <div class="card-header"></div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-12">
            <div class="input-group">
              <div class="input-group-prepend">
                  <span class="input-group-text"><%= icon("search") %></i></span>
                </div>
              <input data-action="keyup->repos#filter" data-target="repos.input" type="text" class="form-control" placeholder="Filter...">
            </div>
          </div>
          <div class="col-sm-12 mt-1">
            <p>
              Not finding what you are looking for? You might need to re-authorize
              AlloyCI for a particular organization. Click the button below to do so.
              Once authorized, please refresh this page.
            </p>
            <%= link to: reauth_url(), target: "_blank", class: "btn btn-secondary btn-sm" do %>
              <%= icon("rocket") %>
              Authorize AlloyCI
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div id="repos-container">
      <div class="row">
        <div class="h3 col-6 offset-4-5">
          <%= icon("spinner", "fa-spin") %>
          Fetching your repositories...
        </div>
      </div>
    </div>
  </div>
</div>

lib/alloy_ci/web/templates/project/show_repo.html.eex
<div class="col-sm-12 col-md-6 col-xl-4" id="card-<%= @repo["id"] %>">
  <div class="card card-border-color card-border-color-dark">
    <div class="card-body">
      <div class="h3 pull-right">
        <%= fork_icon(@repo["fork"]) %>
      </div>
      <div class="h2 text-muted text-xs-right">
        <%= repo_icon(@repo["owner"]["type"]) %>
      </div>
      <div class="h3 m-b-0">
        <div class="filter inline" data-id="<%= @repo["id"] %>">
          <%= @repo["name"] %>
        </div>
        <small><%= privacy_icon(@repo["private"]) %></small>
      </div>
      <span class="text-muted text-uppercase font-weight-bold m-b-2"><%= @repo["owner"]["login"] %></span>
    </div>
  </div>
</div>